version: '2'

services:
    angular:
        build: angular-client
        ports:
            - "4200:4200"

    express:
        build: expres-server
        ports:
            - "3000:3000"

    database:
        image: mongo
        ports:
            - "27017:27017"

